#!/usr/bin/with-contenv bash

if [ -n "${UMASK_SET}" ] && [ -z "${UMASK}" ]; then
  echo -e "You are using a legacy method of defining umask\nplease update your environment variable from UMASK_SET to UMASK\nto keep the functionality after July 2021"
  umask ${UMASK_SET}
fi

if [ -z "${GUI_PORT}" ]; then
	GUI_PORT=8384
fi

exec \
	s6-setuidgid abc syncthing \
	-home=/config -no-browser -no-restart \
	--gui-address="0.0.0.0:${GUI_PORT}"
